config/routes.rb
Hackduke2013::Application.routes.draw do
  match "sessions/destroy" => "sessions#destroy", via: [:get], as: 'signout'

get "sessions/new", as: 'signin'

post "likes/stash"
post "stashes/newpost"

get "stashes/search"

  resources :sessions 
  resources :users
  resources :stashes
  resources :post
  
  get 'users/:username', to: 'users#show'
  get 'recent', to: 'index#recent'
  

  root :to => 'index#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :stash

end

app/models/session.rb
class Session < ActiveRecord::Base
end

app/models/stash.rb
class Stash < ActiveRecord::Base
	belongs_to :user
	has_many :posts, dependent: :destroy

    validates :name,  presence: true

    def self.search(search)
  if search
    find(:all, :conditions => ['LOWER(name) LIKE ?', "%#{search}%".downcase])
  else
    find(:all)
  end
end
end

app/models/stash_like.rb
class StashLike < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :stashes, dependent: :destroy
	before_save { self.email = email.downcase }
	before_save { self.name = name.downcase }
	has_secure_password  

VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
VALID_USERNAME_REGEX = /\A[\S]+\Z/

validates :name,  presence: true, format: { with: VALID_USERNAME_REGEX }, uniqueness: { case_sensitive: false }
validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
validates :password,  presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def current_user  
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]  
  end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(signin_url, notice:'Incorrect User') unless current_user==@user
    end

def signed_in
	if current_user.nil?
		store_location
  	 	redirect_to signin_url, notice: "Please sign in."
	end
end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end

  helper_method :current_user, :correct_user, :signed_in


end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    @title="Popular Stashes"
  	@stashes=Stash.order(score: :desc).limit(8)
  end

  def recent
    @title = "Recent Stashes"
    @stashes = Stash.order(created_at: :desc).limit(8)
    render 'index'
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
      before_action :signed_in

    def stash
        uid=current_user.id
        sid=params[:stash_id]
        stash=Stash.find(sid)

        result=StashLike.where(user_id: uid, stash_id: sid)
        if result.length>0
            result[0].destroy
            stash.score-=1
        else
            StashLike.create(user_id: uid, stash_id: sid)
            stash.score+=1
        end
        stash.save
        response={}
        response["score"]=Stash.find(sid).score
        render json: response
    end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def create
        post_params[:user_id]=current_user.id
  	post=Post.new(post_params)
        post.save
        render :nothing=>true
  end

  def post_params
    params.require(:post).permit(:url)
  end

  def destroy
    post = Post.find(params[:id])
    stash=Stash.find(post.stash_id)
    response = {}
    if stash.user_id ==current_user.id
      post.destroy
      post.save
      response["deleted"]=true
      render json: response
    else
      response["deleted"]=false
      render json: response
    end
    
  end

end

app/controllers/recent_controller.rb
class RecentController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def new
end

  # POST /sessions
  # POST /sessions.json
  def create
   user = User.find_by_name(params[:name])  
  if user && user.authenticate(params[:password])  
    session[:user_id] = user.id  
    redirect_back_or root_url
  else  
    flash[:notice]="Invalid name or password"
    redirect_to :action=>"new"
  end  
  end

  # DELETE /sessions/1
  # DELETE /sessions/1.json
  def destroy
    session[:user_id] = nil  
    redirect_to root_url 
  end
  
end

app/controllers/stash_controller.rb
class StashController < ApplicationController
  def show
    @stash = Stash.find(params[:id])    
  end

def newpost
  require 'mechanize'
  stash=Stash.find(params[:stash][:id])
  u = URI.parse(params[:url])

  if(!u.scheme)
    # prepend http:// and try again
    params[:url].prepend("http://")
      u = URI.parse(params[:url])
  end
if(%w{http https}.include?(u.scheme))
  title=Mechanize.new.get(u.to_s).title
      stash.posts.create(:url=>u.to_s, :title=>title)
      flash[:notice]="Post added to stash!"
      redirect_to :back
else
      flash[:notice]="Error reading URL!"
      redirect_to :back
end
  end

  def update
    @stash = Stash.find(params[:id])
      if @stash.update(stash_params)
        redirect_to @stash, notice: 'Stash was successfully updated.'
      else
        redirect_to @stash, notice: 'Error updating stash.'
      end
  end

  def destroy
    stash = Stash.find(params[:id])
    response = {}
    if stash.user_id ==current_user.id
      stash.destroy
      stash.save
      response["deleted"]=true
      render json: response
    else
      response["deleted"]=false
      render json: response
    end
  end

      # Never trust parameters from the scary internet, only allow the white list through.
    def stash_params
      params.require(:stash).permit(:name, :comment)
    end

end

app/controllers/stashes_controller.rb
class StashesController < ApplicationController
  def show
    @stash = Stash.find(params[:id])    
  end

  def search
  @stashes = Stash.search(params[:search])
end

def create
  @stash=current_user.stashes.create(:name=>params[:stash][:name], :user_id=>current_user.id, :score=>0, :comment=>"Edit to add a description.")
      if @stash.save
        flash[:notice]="Stash created!"
      else
        flash[:notice]="Error creating stash"
      end
        redirect_to :back
end

def newpost
  require 'mechanize'
  stash=Stash.find(params[:stash][:id])
  u = URI.parse(params[:url])

  if(!u.scheme)
    # prepend http:// and try again
    params[:url].prepend("http://")
      u = URI.parse(params[:url])
  end
if(%w{http https}.include?(u.scheme))
  title=Mechanize.new.get(u.to_s).title
      stash.posts.create(:url=>u.to_s, :title=>title)
      flash[:notice]="Post added to stash!"
      redirect_to :back
else
      flash[:notice]="Error reading URL!"
      redirect_to :back
end
  end

  def update
    @stash = Stash.find(params[:id])
      if @stash.update(stash_params)
        redirect_to @stash, notice: 'Stash was successfully updated.'
      else
        redirect_to @stash, notice: 'Error updating stash.'
      end
  end

  def destroy
    stash = Stash.find(params[:id])
    response = {}
    if stash.user_id ==current_user.id
      stash.destroy
      stash.save
      response["deleted"]=true
      render json: response
    else
      response["deleted"]=false
      render json: response
    end
  end

      # Never trust parameters from the scary internet, only allow the white list through.
    def stash_params
      params.require(:stash).permit(:name, :comment)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  before_action :signed_in, only: [:newpost]

  # GET /users/1
  # GET /users/1.json
  def show
    @stashes=Stash.where(user_id: @user.id).reverse_order
    @stash=Stash.new
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to @user
      else
        render action: 'new'
      end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hoard_helper.rb
module HoardHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/recent_helper.rb
module RecentHelper
end

app/helpers/stash_helper.rb
module StashHelper
end

app/views/hoard/index.html.erb
hihihi this is <%= @user.name %>'s hoard.
<%= render partial:"post/post_form" %>

app/views/index/index.html.erb
<div class="title-block">
  <h1><%=@title%></h1>
</div>

<div class="row" style="margin-left:15px;"> <!-- Your Stashes -->
	<% if @stashes.nil?%>
		<p>There are no stashes.</p>
	<% else%>
  <%= render partial:"shared/stash_display", locals:{stashes: @stashes} %>

  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Stash</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="A place to hoard shit">
  <meta name="author" content="Howard Chung, Kevin Jian, Alex Pien">

  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link rel="stylesheet"
  href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
  <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed' rel='stylesheet' type='text/css'>
  <script src="//code.jquery.com/jquery-1.10.1.min.js"></script>
  <style>
    .caption{
      word-wrap: break-word;
    }
    .col-xs-3, .col-xs-12{
      padding-bottom: 30px;
    }
    .like{
      /*visibility: hidden;*/
      position: absolute;
      top: 8px;
      left: 22px;
    }
    .trash{
      position:absolute;
      top: 8px;
      left: 213px;
    }
    footer{
      position: static;
      bottom: 0;
      width: 100%;
      text-align: center;
    }
  </style>
</head>
<body>
  <!-- Static navbar -->
  <div class="navbar navbar-default">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%=link_to "stash", root_url, :class=>"navbar-brand"%>
    </div>

    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "recent","/recent"%></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%if current_user.nil?%>
          <li><%= link_to "Sign in",signin_url%></li>
        <%else%>
        <li><%= render partial:"post/post_form" %></li>
          <li><%=link_to current_user.name, user_path(current_user)%></li>
          <li><%= link_to "Sign out",signout_url%></li>
        <%end%>

      </ul>
    </div><!--/.nav-collapse -->
  </div>

  <div class="container">
    <% if flash[:notice] %>  
 <div class="alert alert-success">
  <%=flash[:notice]%>
 </div>
 <% end %> 
    <%= yield %>
  </div><!--/container-->

 
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>

  <footer>

<%= form_tag "/stashes/search", :method => 'get' do %>
<p>
<div class="form-group">
<%= text_field_tag :search, params[:search] %>
<%= submit_tag "Search", :name => nil, :class=>"btn btn-primary" %>
</div>
</p>
<% end %>

<a class="coinbase-button" data-code="6f165d760fbf055c8d3ac3bf35a694a8" data-button-style="donation_large" href="https://coinbase.com/checkouts/6f165d760fbf055c8d3ac3bf35a694a8">Donate Bitcoins</a><script src="https://coinbase.com/assets/button.js" type="text/javascript"></script>

</footer>

</body>

</html>

app/views/post/_post_form.html.erb
<%stashes=Stash.where(user_id: current_user.id)%>
<% if stashes.length==0%>
<%=link_to "You don't have a stash!", user_path(current_user.id)%>
<%else%>
<%= form_tag("/stashes/newpost", :method => "post", :class=>"navbar-form navbar-right") do %>
<div class="form-group">
  <%= text_field_tag(:url, nil, {:placeholder=>"URL",:class=>"form-control"}) %>
</div>
<div class="form-group">
	<%=collection_select(:stash, :id, stashes, :id, :name, {}, :class =>"form-control")%>
	</div>
<div class="form-group">
  <%= submit_tag("Add Post",  :class=>"btn btn-success") %>
</div>
<% end %>
<%end%>

app/views/shared/_stash_display.html.erb
<% stashes.each do |stash| %>
  <div id="stash-col-<%=stash.id%>"class="col-xs-3" style="width:270px;">
    <div id ="thumb-<%=stash.id%>" class="thumbnail">
      <a href="/stashes/<%= stash.id%>">
        <% if stash.posts.first%>
          <img src="http://api.webthumbnail.org/?width=230&format=png&url=<%=stash.posts.first.url%>"/>
        <% else %>
          <img src="http://i.imgur.com/jnsATLs.png"/>
        <% end %>            </a>
      <div id="like-<%=stash.id%>" class="btn btn-default btn-sm like buttons-<%=stash.id%> hide"  >
        <% if current_user%>
          <span id="icon-<%=stash.id%>" class="glyphicon 
            <% if StashLike.exists?(:stash_id=>stash.id,:user_id=>current_user.id)%>glyphicon-heart<%else%>glyphicon-heart-empty<%end%>"></span>
        <% end %>
        <span id="num-likes-<%=stash.id%>"> <%=stash.score%></span>
      </div>
        <% if current_user %>
          <% if current_user.id==stash.user_id%>
            <div id="delete-<%=stash.id%>" class="btn delete buttons-<%=stash.id%> hide btn-default btn-sm delete trash">
            <span  class="glyphicon glyphicon-trash"></span>
            </div>
          <% end %>
        <% end %>
    <div class="caption">
        <h3 class="postTitle"> <%= stash.name %> </h3>
      <p class="postAuthor"> by <%= link_to User.find(stash.user_id).name, user_path(stash.user_id)%></p>
      <p class="postAuthor"><%="Links: "+stash.posts.length.to_s%></p>
    </div>

    </div>
  </div>
<% end %>

app/views/stash/show.html.erb
<div class="title-block"><h1><%=@stash.name%></h1> <span style="margin-left:5em">by <%=link_to User.find(@stash.user_id).name, user_path(@stash.user_id)%></span></div>
<%if current_user%>
  <button type="button" class="btn btn-default editButton">Edit</button>
  <div class ="stashCommentEdit" style="display:none;">
    <%= render partial:"stash/stash_update" %>
  </div>
<%end%>


<p class="lead text-muted"><%=@stash.comment%></p>


<div style="margin-left:15px;">
  <% Post.where(stash_id: @stash.id).each do |post|%>
  <div id="post-col-<%=post.id%>"class="col-xs-3" style="width:270px;">
    <div id ="thumb-<%=post.id%>-post" class="thumbnail">
      <a href="<%= post.url%>">
	<img src="http://api.webthumbnail.org/?width=230&format=png&url=<%=post.url%>"/>
 </a>
              <% if current_user %>
    <div id="delete-<%=post.id%>-post" class="btn delete-post buttons-<%=post.id%>
                                          hide btn-default btn-sm trash" style="float:right">
        <span  class="glyphicon glyphicon-trash"></span>
    </div>
    <% end %>
            
      <div class="caption" style="word-wrap: break-word;;">
	<h4 style="text-wrap:unrestricted;"><%= post.title %>  </h4>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/stashes/_stash_form.html.erb
<div class="row">
<%= form_for(@stash, :class=>"form-inline") do |f|%>
<div class="col-xs-3">
  <%= f.text_field(:name, {:placeholder=>"Add a Stash",:class=>"form-control"}) %>
</div>
  <%= f.submit("Add", :class=>"btn btn-success") %>
<% end %>
</div>

app/views/stashes/_stash_update.html.erb
<%= form_for(@stash) do |f|%>
<div class="form-group">
  <%= f.text_field(:name, {:placeholder=>"Name",:class=>"form-control"}) %>
</div>
<div class="form-group">
  <%= f.text_area(:comment, {:placeholder=>"Description",:class=>"form-control"}) %>
</div>
<div class="form-group">
  <%= f.submit("Update",  :class=>"btn btn-success") %>
</div>
<% end %>

app/views/stashes/search.html.erb
  <h4>Results for: <%=params[:search]%></h4>
<% if @stashes.length==0%>
  <h4>There are no stashes!</h4>
<% else%>
  <%= render partial:"shared/stash_display", locals:{stashes: @stashes} %>
<% end%>

app/views/stashes/show.html.erb
<div class="stash-header">
  
<% if current_user %>
<% if @stash.user_id == current_user.id %>
<div id="edit"> edit </div>
<% end %>
<% end %>
</div>

    <div id="shown">
      <!-- front content -->
      <div class="title-block"><h1><%=@stash.name%></h1> <span style="margin-left:5em">by
          <%=link_to User.find(@stash.user_id).name,
                     user_path(@stash.user_id)%></span></div>
      <div class="comments">
        <%=@stash.comment%>
      </div>

    </div>
    <div id="editmsg" style="display:none">
      <!-- back content -->
        <%= render partial:"stashes/stash_update" %>
</div>

<div style="margin-left:15px;">
  <% Post.where(stash_id: @stash.id).each do |post|%>
  <div id="post-col-<%=post.id%>"class="col-xs-3" style="width:270px;">
    <div id ="thumb-<%=post.id%>-post" class="thumbnail">
      <a href="<%= post.url%>">
	<img src="http://api.webthumbnail.org/?width=230&format=png&url=<%=post.url%>"/>
 </a>
              <% if current_user %>
              <% if Stash.find(post.stash_id).user_id == current_user.id%>
    <div id="delete-<%=post.id%>-post" class="btn delete-post buttons-<%=post.id%>
                                          hide btn-default btn-sm trash" style="float:right">
        <span  class="glyphicon glyphicon-trash"></span>
    </div>
    <% end %>
    <% end %>
            
      <div class="caption" style="word-wrap: break-word;;">
	<h4 style="text-wrap:unrestricted;"><%= post.title %>  </h4>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>  
  <% if @user.errors.any? %>  
  <div class="alert alert-danger">
          <h3><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
             <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
        </div>
  <% end %>  
    <div class="form-group">  
    <%= f.text_field :name,{:class=>"form-control",:placeholder=>"Username"}  %>  
  </div>  
  <div class="form-group">  
    <%= f.text_field :email,{:class=>"form-control",:placeholder=>"Email"}  %>  
  </div>  
  <div class="form-group">  
    <%= f.password_field :password,{:class=>"form-control",:placeholder=>"Password"}  %>  
  </div>  
  <div class="form-group">  
    <%= f.password_field :password_confirmation,{:class=>"form-control",:placeholder=>"Confirm"}  %>  
  </div>  
  <div class="form-group">
    <%= f.submit "Submit" ,:class=>"btn btn-primary"%>
  </div>  
<% end %> 

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<div class="row">
	<div class="col-md-4"></div>
	 <div class="col-md-4">
	 	<h2>Sign up</h2>
		<%=render 'form'%>
	</div>
	<div class="col-md-4"></div>
</div>

app/views/users/show.html.erb
<h3>
  <strong>stasher:</strong>
  <%= @user.name %>
</h3>

<h3>
  <strong>email:</strong>
  <%= @user.email %>
</h3>

<h3>
  <strong>score:</strong>
  <%= @user.stashes.sum(:score) %>
</h3>


<% if current_user %>
<% if current_user.name==@user.name %>


<div class="title-block">
<div style="float:left;">
<h1 >
  Your Stashes
</h1>
</div>
</div>
<div>
 <%= render partial:"stashes/stash_form" %>
</div>
<% end %>
<% end %> 

<% if @stashes.length==0%>
  <h4>There are no stashes!</h4>
<% else%>
  <%= render partial:"shared/stash_display", locals:{stashes: @stashes} %>
<% end%>